export const SOCKET_EVENTS = {
  // connection
  NEW_USER_JOINED:   'new-user-joined',
  USER_CONNECTED:    'user-connected',
  USER_DISCONNECTED: 'user-disconnected',
  USER_LIST:         'user-list',

  // contacts
  CONTACT_LIST:      'contactList',
  CONTACTS_LISTS:    'contactsLists',
  CONTACT_DELETE:    'contact_delete',
  SEARCH_CONTACT:    'searchContactValue',
  CONTACT_BY_USER:   'contactByUser',
  CONTACT_INFO:      'contactInfo',
  SUCCESS:           'Success',
  CONTACTS_ERROR:    'contactsError',

  // single chat
  CHAT_MESSAGE:       'chat message',
  MESSAGE_UPDATE:     'message_update',
  MESSAGE_DELETE:     'message_delete',
  USER_CLICK:         'userClick',
  USER_MESSAGE:       'userMessage',
  CHAT_PG:            'chat-pg',
  IS_MESSAGE:         'isMessage',
  TYPING:             'typing',
  UNREAD_MSG_UPDATE:  'unreadMsgUpdate',
  ALL_MSG_DELETE:     'all_Message_delete',
  RECEIVER_ID:        'receiverId',
  RECEIVER_DATA:      'receiver_data',
  CHAT_ONLINE:        'chat_online',
  ONLINE_USER:        'onlineUser',
  ROOM_USERS:         'roomUsers',
  EDIT_AND_UPDATE:    'editandupdate',

  // groups
  CREATE_GROUP:           'createGroups',
  GROUP_ADD:              'group-add',
  GROUP_LISTS:            'groupLists',
  GROUP_MESSAGE:          'group message',
  GROUP_MESSAGE_EVT:      'groupMessage',
  GCHAT_PG:               'gchat-pg',
  GROUP_MSG_UPDATE:       'groupMessage_update',
  GROUP_MSG_DELETE:       'group_msg_delete',
  GROUP_DELETE:           'group_delete',
  GROUP_DELETE_MEMBER:    'group_delete_member',
  DELETE_GROUP_USER:      'deleteGroupUser',
  ALL_GROUP_MSG_DELETE:   'all_Group_Message_delete',
  SINGLE_GROUP_MSG_DELETE:'single_Group_Message_delete',
  GROUP_SENDER_MSG:       'groupSenderMessage',
  GROUP_CLICK:            'groupClick',
  GROUP_INFO:             'groupInfo',
  GROUP_DETAIL:           'groupDetail',
  GROUP_TYPING:           'group_typing',
  ADD_GROUP_CONTACTS:     'addGroupContacts',
  ADD_GROUP:              'addGroup',
  SEARCH_GROUP:           'searchGroupValue',
  SEARCH_GROUP_VAL:       'searchGroupValue',
  ONLINE_USER_GROUP:      'online_user',
  ONLINE_CONTACT:         'onlineContact',
  UNREAD_GROUP_UPDATE:    'unreadGroupMsgUpdate',
  CONTACT_ID_BY_USER:     'contactIdByUser',
  CONTACTS_DETAIL:        'contactsDetail',

  // user / settings
  CURRENT_USER:           'currentUser',
  UPDATE_USERNAME:        'updateUserName',
  UPDATE_RECEIVER_NAME:   'updateReceiverName',
  UPDATE_GROUP_NAME:      'updateGroupName',
  USER_NOTIFICATION:      'userNotification',
  USER_MUTED:             'userMutedNotification',
  MESSAGE_UPDATE1:        'message_update1',

  // calls
  RING_CALL:    'ringcall',
  RING_CALLING: 'ringcalling',
  ANSWERED:     'answerd',
  ANSWER_EVT:   'answered',
  CUT_PHONE:    'cutphone',
  CUT_PHONES:   'cutphoness',
  CUT_ANSWERED: 'cutanswerd',
  CUT_PEER:     'cutpeeranswer',
  IS_BUSY:      'isbusy',
  IT_BUSY:      'itbusy',
  CLOSE_VC:     'closevc',
  CUT_VC:       'cutvc',
  VC_CALL_MSG:  'vccallmsg',
  GETING_MSGS:  'getingonmsgs',
} as const;
